version: "3.9"

services:
  frontend:
    build:
      context: ./client  # Path to the frontend folder
      dockerfile: Dockerfile  # Dockerfile inside the frontend folder
    ports:
      - "5173:80"  # Expose frontend on port 5173
    depends_on:
      - backend  # Wait for backend to start
    environment:
      - VITE_SERVER_URL=http://backend:2668  # API URL for frontend to communicate with backend

  backend:
    build:
      context: ./server  # Path to the backend folder
      dockerfile: Dockerfile  # Dockerfile inside the backend folder
    ports:
      - "2668:2668"
    environment:
      - NODE_ENV=development  # Backend running in development mode
    volumes:
      - ./server:/app  # Mount local code to container for live reloading
      - /app/node_modules  # Avoid overwriting node_modules
    command: npm run dev  # Start the backend with `npm run dev`
    networks:
      - backend_network  # Custom network for backend communication

# Define the custom network for service communication (here i struggled a lot)
networks:
  backend_network:
    driver: bridge

